# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Attendee Answer

# Model Form Field configuration
form: $/pensoft/eventsextension/models/attendeeanswer/fields.yaml

# Model Class name
modelClass: Pensoft\Eventsextension\Models\AttendeeAnswer

# Default redirect location
defaultRedirect: pensoft/eventsextension/attendeeanswers

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/eventsextension/attendeeanswers/update/:id
    redirectClose: pensoft/eventsextension/attendeeanswers

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/eventsextension/attendeeanswers
    redirectClose: pensoft/eventsextension/attendeeanswers

# Preview page
preview:
    title: backend::lang.form.preview_title
