# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Attendee Question

# Model Form Field configuration
form: $/pensoft/eventsextension/models/attendeequestion/fields.yaml

# Model Class name
modelClass: Pensoft\Eventsextension\Models\AttendeeQuestion

# Default redirect location
defaultRedirect: pensoft/eventsextension/attendeequestions

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/eventsextension/attendeequestions/update/:id
    redirectClose: pensoft/eventsextension/attendeequestions

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/eventsextension/attendeequestions
    redirectClose: pensoft/eventsextension/attendeequestions

# Preview page
preview:
    title: backend::lang.form.preview_title
