# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Status

# Model Form Field configuration
form: $/pensoft/eventsextension/models/status/fields.yaml

# Model Class name
modelClass: Pensoft\Eventsextension\Models\Status

# Default redirect location
defaultRedirect: pensoft/eventsextension/statuses

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/eventsextension/statuses/update/:id
    redirectClose: pensoft/eventsextension/statuses

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/eventsextension/statuses
    redirectClose: pensoft/eventsextension/statuses

# Preview page
preview:
    title: backend::lang.form.preview_title
